-- Données initiales Repareliya (générées le 2026-09-25)
-- Catalogue de départ : les modèles Apple viennent d'AppleDB, les modèles Android
-- reprennent les noms commerciaux de la liste Google Play. Le reste du catalogue
-- s'importe depuis le tableau de bord (Appareils → Importer).
-- Aucun prix n'est inventé : chaque tarif est à saisir dans le tableau de bord.

insert into public.device_categories (slug, name, description, icon, sort_order) values
  ('smartphones', 'Smartphones', 'Écran, batterie, connecteur, caméra…', 'smartphone', 1),
  ('tablettes', 'Tablettes', 'iPad, Galaxy Tab et autres tablettes', 'tablet', 2),
  ('ordinateurs', 'Ordinateurs', 'MacBook et ordinateurs portables', 'laptop', 3),
  ('consoles', 'Consoles & manettes', 'PlayStation, Nintendo Switch, Xbox, manettes', 'gamepad', 4),
  ('montres', 'Montres connectées', 'Apple Watch, Galaxy Watch…', 'watch', 5)
on conflict (slug) do nothing;

insert into public.brands (slug, name, sort_order, is_featured) values
  ('apple', 'Apple', 1, true),
  ('samsung', 'Samsung', 2, true),
  ('xiaomi', 'Xiaomi', 3, true),
  ('huawei', 'Huawei', 4, true),
  ('google', 'Google', 5, true),
  ('oppo', 'Oppo', 6, true),
  ('honor', 'Honor', 7, true),
  ('oneplus', 'OnePlus', 8, false),
  ('motorola', 'Motorola', 9, false),
  ('realme', 'realme', 10, false),
  ('vivo', 'vivo', 11, false),
  ('tecno', 'Tecno', 12, false),
  ('infinix', 'Infinix', 13, false),
  ('sony', 'Sony', 20, true),
  ('nintendo', 'Nintendo', 21, true),
  ('microsoft', 'Microsoft', 22, true),
  ('valve', 'Valve', 23, false)
on conflict (slug) do nothing;

insert into public.repair_types (slug, name, description, icon, sort_order) values
  ('ecran', 'Écran', 'Remplacement de l’écran cassé, tactile ou affichage défectueux.', 'screen', 1),
  ('batterie', 'Batterie', 'Batterie qui se vide vite, gonflée ou appareil qui s’éteint.', 'battery', 2),
  ('connecteur-charge', 'Connecteur de charge', 'L’appareil ne charge plus ou seulement dans une position.', 'plug', 3),
  ('vitre-arriere', 'Vitre arrière', 'Remplacement de la face arrière fissurée.', 'layers', 4),
  ('camera-arriere', 'Caméra arrière', 'Photos floues, taches ou caméra qui ne s’ouvre plus.', 'camera', 5),
  ('camera-avant', 'Caméra avant / Face ID', 'Caméra selfie, Face ID ou capteurs de proximité.', 'scan-face', 6),
  ('haut-parleur', 'Haut-parleur / écouteur', 'Son faible, grésillements ou plus de son en appel.', 'volume', 7),
  ('micro', 'Micro', 'Vos correspondants ne vous entendent plus.', 'mic', 8),
  ('boutons', 'Boutons', 'Bouton power, volume ou vibreur bloqué.', 'toggle', 9),
  ('clavier', 'Clavier / trackpad', 'Touches bloquées, clavier ou trackpad hors service.', 'keyboard', 10),
  ('hdmi', 'Port HDMI', 'Plus d’image sur la télévision.', 'hdmi', 11),
  ('joystick', 'Joystick / drift', 'Joystick qui dérive, gâchettes ou boutons de manette.', 'gamepad', 12),
  ('nettoyage', 'Nettoyage & pâte thermique', 'Surchauffe, ventilateur bruyant, poussière.', 'fan', 13),
  ('desoxydation', 'Désoxydation', 'Appareil tombé dans l’eau ou exposé à l’humidité.', 'droplets', 14),
  ('carte-mere', 'Micro-soudure / carte mère', 'Pannes électroniques, composants, puces.', 'cpu', 15),
  ('logiciel', 'Logiciel & données', 'Mise à jour, appareil bloqué, sauvegarde et transfert de données.', 'code', 16),
  ('diagnostic', 'Diagnostic', 'Vous ne savez pas d’où vient la panne ? On cherche pour vous.', 'search', 17)
on conflict (slug) do nothing;

insert into public.repair_type_categories (repair_type_id, category_id)
select r.id, c.id from (values
  ('ecran', 'smartphones'),
  ('ecran', 'tablettes'),
  ('ecran', 'ordinateurs'),
  ('ecran', 'consoles'),
  ('ecran', 'montres'),
  ('batterie', 'smartphones'),
  ('batterie', 'tablettes'),
  ('batterie', 'ordinateurs'),
  ('batterie', 'consoles'),
  ('batterie', 'montres'),
  ('connecteur-charge', 'smartphones'),
  ('connecteur-charge', 'tablettes'),
  ('connecteur-charge', 'consoles'),
  ('vitre-arriere', 'smartphones'),
  ('vitre-arriere', 'montres'),
  ('camera-arriere', 'smartphones'),
  ('camera-arriere', 'tablettes'),
  ('camera-avant', 'smartphones'),
  ('camera-avant', 'tablettes'),
  ('haut-parleur', 'smartphones'),
  ('haut-parleur', 'tablettes'),
  ('haut-parleur', 'ordinateurs'),
  ('micro', 'smartphones'),
  ('micro', 'tablettes'),
  ('boutons', 'smartphones'),
  ('boutons', 'tablettes'),
  ('boutons', 'consoles'),
  ('boutons', 'montres'),
  ('clavier', 'ordinateurs'),
  ('hdmi', 'consoles'),
  ('joystick', 'consoles'),
  ('nettoyage', 'consoles'),
  ('nettoyage', 'ordinateurs'),
  ('desoxydation', 'smartphones'),
  ('desoxydation', 'tablettes'),
  ('desoxydation', 'ordinateurs'),
  ('desoxydation', 'consoles'),
  ('desoxydation', 'montres'),
  ('carte-mere', 'smartphones'),
  ('carte-mere', 'tablettes'),
  ('carte-mere', 'ordinateurs'),
  ('carte-mere', 'consoles'),
  ('carte-mere', 'montres'),
  ('logiciel', 'smartphones'),
  ('logiciel', 'tablettes'),
  ('logiciel', 'ordinateurs'),
  ('logiciel', 'consoles'),
  ('logiciel', 'montres'),
  ('diagnostic', 'smartphones'),
  ('diagnostic', 'tablettes'),
  ('diagnostic', 'ordinateurs'),
  ('diagnostic', 'consoles'),
  ('diagnostic', 'montres')
) as v(repair_slug, category_slug)
join public.repair_types r on r.slug = v.repair_slug
join public.device_categories c on c.slug = v.category_slug
on conflict do nothing;

-- 429 modèles
insert into public.device_models (brand_id, category_id, name, slug, release_year, sort_order, is_popular, source)
select b.id, c.id, v.name, v.slug, v.release_year, v.sort_order, v.is_popular, v.source from (values
  ('apple', 'smartphones', 'iPhone 18 Pro', 'iphone-18-pro', 2026, 1, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 18 Pro Max', 'iphone-18-pro-max', 2026, 2, true, 'appledb'),
  ('apple', 'montres', 'Watch Series 12 (42mm)', 'watch-series-12-42mm', 2026, 1, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 12 (46mm)', 'watch-series-12-46mm', 2026, 2, false, 'appledb'),
  ('apple', 'montres', 'Watch Ultra 4', 'watch-ultra-4', 2026, 3, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Air 11 pouces (M4)', 'ipad-air-11-pouces-m4', 2026, 1, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Air 13 pouces (M4)', 'ipad-air-13-pouces-m4', 2026, 2, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 17e', 'iphone-17e', 2026, 3, true, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (13 pouces, M5)', 'macbook-air-13-pouces-m5', 2026, 1, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (15 pouces, M5)', 'macbook-air-15-pouces-m5', 2026, 2, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Neo', 'macbook-neo', 2026, 3, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M5 Max)', 'macbook-pro-14-pouces-m5-max', 2026, 4, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M5 Pro)', 'macbook-pro-14-pouces-m5-pro', 2026, 5, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M5 Max)', 'macbook-pro-16-pouces-m5-max', 2026, 6, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M5 Pro)', 'macbook-pro-16-pouces-m5-pro', 2026, 7, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 11 pouces (M5)', 'ipad-pro-11-pouces-m5', 2025, 3, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 13 pouces (M5)', 'ipad-pro-13-pouces-m5', 2025, 4, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro 14 pouces (M5)', 'macbook-pro-14-pouces-m5', 2025, 8, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 17', 'iphone-17', 2025, 4, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 17 Pro', 'iphone-17-pro', 2025, 5, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 17 Pro Max', 'iphone-17-pro-max', 2025, 6, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone Air', 'iphone-air', 2025, 7, false, 'appledb'),
  ('apple', 'montres', 'Watch SE 3 (40mm)', 'watch-se-3-40mm', 2025, 4, false, 'appledb'),
  ('apple', 'montres', 'Watch SE 3 (44mm)', 'watch-se-3-44mm', 2025, 5, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 11 (42mm)', 'watch-series-11-42mm', 2025, 6, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 11 (46mm)', 'watch-series-11-46mm', 2025, 7, false, 'appledb'),
  ('apple', 'montres', 'Watch Ultra 3', 'watch-ultra-3', 2025, 8, false, 'appledb'),
  ('apple', 'tablettes', 'iPad (A16)', 'ipad-a16', 2025, 5, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Air 11 pouces (M3)', 'ipad-air-11-pouces-m3', 2025, 6, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Air 13 pouces (M3)', 'ipad-air-13-pouces-m3', 2025, 7, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (13 pouces, M4, 2025)', 'macbook-air-13-pouces-m4-2025', 2025, 9, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (15 pouces, M4, 2025)', 'macbook-air-15-pouces-m4-2025', 2025, 10, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 16e', 'iphone-16e', 2025, 8, true, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M4 Max, nov. 2024)', 'macbook-pro-14-pouces-m4-max-nov-2024', 2024, 11, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M4 Pro, nov. 2024)', 'macbook-pro-14-pouces-m4-pro-nov-2024', 2024, 12, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M4, nov. 2024)', 'macbook-pro-14-pouces-m4-nov-2024', 2024, 13, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M4 Max, nov. 2024)', 'macbook-pro-16-pouces-m4-max-nov-2024', 2024, 14, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M4 Pro, nov. 2024)', 'macbook-pro-16-pouces-m4-pro-nov-2024', 2024, 15, false, 'appledb'),
  ('apple', 'tablettes', 'iPad mini (A17 Pro)', 'ipad-mini-a17-pro', 2024, 8, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 16', 'iphone-16', 2024, 9, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 16 Plus', 'iphone-16-plus', 2024, 10, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 16 Pro', 'iphone-16-pro', 2024, 11, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 16 Pro Max', 'iphone-16-pro-max', 2024, 12, true, 'appledb'),
  ('apple', 'montres', 'Watch Series 10 (42mm)', 'watch-series-10-42mm', 2024, 9, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 10 (46mm)', 'watch-series-10-46mm', 2024, 10, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Air 11 pouces (M2)', 'ipad-air-11-pouces-m2', 2024, 9, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Air 13 pouces (M2)', 'ipad-air-13-pouces-m2', 2024, 10, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 11 pouces (M4)', 'ipad-pro-11-pouces-m4', 2024, 11, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 13 pouces (M4)', 'ipad-pro-13-pouces-m4', 2024, 12, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (13 pouces, M3, 2024)', 'macbook-air-13-pouces-m3-2024', 2024, 16, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (15 pouces, M3, 2024)', 'macbook-air-15-pouces-m3-2024', 2024, 17, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M3 Max, nov. 2023)', 'macbook-pro-14-pouces-m3-max-nov-2023', 2023, 18, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M3 Max, nov. 2023)', 'macbook-pro-16-pouces-m3-max-nov-2023', 2023, 19, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M3 Pro, nov. 2023)', 'macbook-pro-14-pouces-m3-pro-nov-2023', 2023, 20, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M3, nov. 2023)', 'macbook-pro-14-pouces-m3-nov-2023', 2023, 21, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M3 Pro, nov. 2023)', 'macbook-pro-16-pouces-m3-pro-nov-2023', 2023, 22, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 15', 'iphone-15', 2023, 13, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 15 Plus', 'iphone-15-plus', 2023, 14, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 15 Pro', 'iphone-15-pro', 2023, 15, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 15 Pro Max', 'iphone-15-pro-max', 2023, 16, true, 'appledb'),
  ('apple', 'montres', 'Watch Series 9 (41mm)', 'watch-series-9-41mm', 2023, 11, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 9 (45mm)', 'watch-series-9-45mm', 2023, 12, false, 'appledb'),
  ('apple', 'montres', 'Watch Ultra 2', 'watch-ultra-2', 2023, 13, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (15 pouces, M2, 2023)', 'macbook-air-15-pouces-m2-2023', 2023, 23, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M2 Max, 2023)', 'macbook-pro-14-pouces-m2-max-2023', 2023, 24, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M2 Pro, 2023)', 'macbook-pro-14-pouces-m2-pro-2023', 2023, 25, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M2 Max, 2023)', 'macbook-pro-16-pouces-m2-max-2023', 2023, 26, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M2 Pro, 2023)', 'macbook-pro-16-pouces-m2-pro-2023', 2023, 27, false, 'appledb'),
  ('apple', 'tablettes', 'iPad (10e génération)', 'ipad-10e-generation', 2022, 13, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 11 pouces (4e génération)', 'ipad-pro-11-pouces-4e-generation', 2022, 14, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 12.9 pouces (6e génération)', 'ipad-pro-12-9-pouces-6e-generation', 2022, 15, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 14 Plus', 'iphone-14-plus', 2022, 17, true, 'appledb'),
  ('apple', 'montres', 'Watch Ultra', 'watch-ultra', 2022, 14, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 14', 'iphone-14', 2022, 18, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 14 Pro', 'iphone-14-pro', 2022, 19, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 14 Pro Max', 'iphone-14-pro-max', 2022, 20, true, 'appledb'),
  ('apple', 'montres', 'Watch SE (2e génération, 40mm)', 'watch-se-2e-generation-40mm', 2022, 15, false, 'appledb'),
  ('apple', 'montres', 'Watch SE (2e génération, 44mm)', 'watch-se-2e-generation-44mm', 2022, 16, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 8 (41mm)', 'watch-series-8-41mm', 2022, 17, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 8 (45mm)', 'watch-series-8-45mm', 2022, 18, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (M2, 2022)', 'macbook-air-m2-2022', 2022, 28, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (13 pouces, M2, 2022)', 'macbook-pro-13-pouces-m2-2022', 2022, 29, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Air (5e génération)', 'ipad-air-5e-generation', 2022, 16, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone SE (3e génération)', 'iphone-se-3e-generation', 2022, 21, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M1 Max, 2021)', 'macbook-pro-14-pouces-m1-max-2021', 2021, 30, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (14 pouces, M1 Pro, 2021)', 'macbook-pro-14-pouces-m1-pro-2021', 2021, 31, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M1 Max, 2021)', 'macbook-pro-16-pouces-m1-max-2021', 2021, 32, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (16 pouces, M1 Pro, 2021)', 'macbook-pro-16-pouces-m1-pro-2021', 2021, 33, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 7 (41mm)', 'watch-series-7-41mm', 2021, 19, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 7 (45mm)', 'watch-series-7-45mm', 2021, 20, false, 'appledb'),
  ('apple', 'tablettes', 'iPad (9e génération)', 'ipad-9e-generation', 2021, 17, false, 'appledb'),
  ('apple', 'tablettes', 'iPad mini (6e génération)', 'ipad-mini-6e-generation', 2021, 18, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 13', 'iphone-13', 2021, 22, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 13 mini', 'iphone-13-mini', 2021, 23, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 13 Pro', 'iphone-13-pro', 2021, 24, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 13 Pro Max', 'iphone-13-pro-max', 2021, 25, true, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 11 pouces (3e génération)', 'ipad-pro-11-pouces-3e-generation', 2021, 19, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 12.9 pouces (5e génération)', 'ipad-pro-12-9-pouces-5e-generation', 2021, 20, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (M1, 2020)', 'macbook-air-m1-2020', 2020, 34, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (13 pouces, M1, 2020)', 'macbook-pro-13-pouces-m1-2020', 2020, 35, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 12 mini', 'iphone-12-mini', 2020, 26, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 12 Pro Max', 'iphone-12-pro-max', 2020, 27, true, 'appledb'),
  ('apple', 'tablettes', 'iPad Air (4e génération)', 'ipad-air-4e-generation', 2020, 21, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 12', 'iphone-12', 2020, 28, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 12 Pro', 'iphone-12-pro', 2020, 29, true, 'appledb'),
  ('apple', 'tablettes', 'iPad (8e génération)', 'ipad-8e-generation', 2020, 22, false, 'appledb'),
  ('apple', 'montres', 'Watch SE (1re génération, 40mm)', 'watch-se-1re-generation-40mm', 2020, 21, false, 'appledb'),
  ('apple', 'montres', 'Watch SE (1re génération, 44mm)', 'watch-se-1re-generation-44mm', 2020, 22, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 6 (40mm)', 'watch-series-6-40mm', 2020, 23, false, 'appledb'),
  ('apple', 'montres', 'Watch Series 6 (44mm)', 'watch-series-6-44mm', 2020, 24, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (13 pouces, 2020, 2 ports Thunderbolt 3)', 'macbook-pro-13-pouces-2020-2-ports-thunderbolt-3', 2020, 36, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Pro (13 pouces, 2020, 4 ports Thunderbolt 3)', 'macbook-pro-13-pouces-2020-4-ports-thunderbolt-3', 2020, 37, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone SE (2e génération)', 'iphone-se-2e-generation', 2020, 30, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 11 pouces (2e génération)', 'ipad-pro-11-pouces-2e-generation', 2020, 23, false, 'appledb'),
  ('apple', 'tablettes', 'iPad Pro 12.9 pouces (4e génération)', 'ipad-pro-12-9-pouces-4e-generation', 2020, 24, false, 'appledb'),
  ('apple', 'ordinateurs', 'MacBook Air (Retina, 13 pouces, 2020)', 'macbook-air-retina-13-pouces-2020', 2020, 38, false, 'appledb'),
  ('apple', 'tablettes', 'iPad (7e génération)', 'ipad-7e-generation', 2019, 25, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 11', 'iphone-11', 2019, 31, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 11 Pro', 'iphone-11-pro', 2019, 32, true, 'appledb'),
  ('apple', 'smartphones', 'iPhone 11 Pro Max', 'iphone-11-pro-max', 2019, 33, true, 'appledb'),
  ('apple', 'tablettes', 'iPad Air (3e génération)', 'ipad-air-3e-generation', 2019, 26, false, 'appledb'),
  ('apple', 'tablettes', 'iPad mini (5e génération)', 'ipad-mini-5e-generation', 2019, 27, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone XR', 'iphone-xr', 2018, 34, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone XS', 'iphone-xs', 2018, 35, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone XS Max', 'iphone-xs-max', 2018, 36, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone X', 'iphone-x', 2017, 37, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 8', 'iphone-8', 2017, 38, false, 'appledb'),
  ('apple', 'smartphones', 'iPhone 8 Plus', 'iphone-8-plus', 2017, 39, false, 'appledb'),
  ('samsung', 'smartphones', 'Galaxy S26 Ultra', 'galaxy-s26-ultra', 2026, 1, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S26+', 'galaxy-s26-plus', 2026, 2, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S26', 'galaxy-s26', 2026, 3, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S26 FE', 'galaxy-s26-fe', 2026, 4, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S25 Ultra', 'galaxy-s25-ultra', 2025, 5, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S25+', 'galaxy-s25-plus', 2025, 6, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S25', 'galaxy-s25', 2025, 7, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S25 Edge', 'galaxy-s25-edge', 2025, 8, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S25 FE', 'galaxy-s25-fe', 2025, 9, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S24 Ultra', 'galaxy-s24-ultra', 2024, 10, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S24+', 'galaxy-s24-plus', 2024, 11, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S24', 'galaxy-s24', 2024, 12, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S24 FE', 'galaxy-s24-fe', 2024, 13, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S23 Ultra', 'galaxy-s23-ultra', 2023, 14, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S23+', 'galaxy-s23-plus', 2023, 15, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S23', 'galaxy-s23', 2023, 16, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S23 FE', 'galaxy-s23-fe', 2023, 17, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S22 Ultra', 'galaxy-s22-ultra', 2022, 18, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S22+', 'galaxy-s22-plus', 2022, 19, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S22', 'galaxy-s22', 2022, 20, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S21 Ultra 5G', 'galaxy-s21-ultra-5g', 2021, 21, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S21+ 5G', 'galaxy-s21-plus-5g', 2021, 22, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S21 5G', 'galaxy-s21-5g', 2021, 23, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S21 FE 5G', 'galaxy-s21-fe-5g', 2022, 24, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S20 Ultra 5G', 'galaxy-s20-ultra-5g', 2020, 25, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S20+', 'galaxy-s20-plus', 2020, 26, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S20', 'galaxy-s20', 2020, 27, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy S20 FE', 'galaxy-s20-fe', 2020, 28, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Fold7', 'galaxy-z-fold7', 2025, 29, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Flip7', 'galaxy-z-flip7', 2025, 30, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Flip7 FE', 'galaxy-z-flip7-fe', 2025, 31, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Fold6', 'galaxy-z-fold6', 2024, 32, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Flip6', 'galaxy-z-flip6', 2024, 33, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Fold5', 'galaxy-z-fold5', 2023, 34, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Flip5', 'galaxy-z-flip5', 2023, 35, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Fold4', 'galaxy-z-fold4', 2022, 36, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Flip4', 'galaxy-z-flip4', 2022, 37, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Fold3 5G', 'galaxy-z-fold3-5g', 2021, 38, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy Z Flip3 5G', 'galaxy-z-flip3-5g', 2021, 39, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A57 5G', 'galaxy-a57-5g', 2026, 40, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A37 5G', 'galaxy-a37-5g', 2026, 41, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A17', 'galaxy-a17', 2025, 42, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A56 5G', 'galaxy-a56-5g', 2025, 43, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A36 5G', 'galaxy-a36-5g', 2025, 44, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A26 5G', 'galaxy-a26-5g', 2025, 45, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A16', 'galaxy-a16', 2024, 46, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A07', 'galaxy-a07', 2025, 47, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A06', 'galaxy-a06', 2024, 48, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A55 5G', 'galaxy-a55-5g', 2024, 49, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A35 5G', 'galaxy-a35-5g', 2024, 50, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A25 5G', 'galaxy-a25-5g', 2023, 51, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A15', 'galaxy-a15', 2023, 52, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A05', 'galaxy-a05', 2023, 53, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A54 5G', 'galaxy-a54-5g', 2023, 54, true, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A34 5G', 'galaxy-a34-5g', 2023, 55, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A24', 'galaxy-a24', 2023, 56, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A14', 'galaxy-a14', 2023, 57, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A53 5G', 'galaxy-a53-5g', 2022, 58, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A33 5G', 'galaxy-a33-5g', 2022, 59, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A23', 'galaxy-a23', 2022, 60, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A13', 'galaxy-a13', 2022, 61, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A73 5G', 'galaxy-a73-5g', 2022, 62, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A52', 'galaxy-a52', 2021, 63, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A32', 'galaxy-a32', 2021, 64, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A22', 'galaxy-a22', 2021, 65, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A12', 'galaxy-a12', 2020, 66, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A72', 'galaxy-a72', 2021, 67, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A71', 'galaxy-a71', 2020, 68, false, 'google_play'),
  ('samsung', 'smartphones', 'Galaxy A51', 'galaxy-a51', 2019, 69, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab S11 Ultra', 'galaxy-tab-s11-ultra', 2025, 1, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab S11', 'galaxy-tab-s11', 2025, 2, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab S10 Ultra', 'galaxy-tab-s10-ultra', 2024, 3, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab S10+', 'galaxy-tab-s10-plus', 2024, 4, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab S10 FE', 'galaxy-tab-s10-fe', 2025, 5, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab S9 Ultra', 'galaxy-tab-s9-ultra', 2023, 6, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab S9+', 'galaxy-tab-s9-plus', 2023, 7, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab S9', 'galaxy-tab-s9', 2023, 8, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab S9 FE', 'galaxy-tab-s9-fe', 2023, 9, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab A11', 'galaxy-tab-a11', 2025, 10, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab A9+', 'galaxy-tab-a9-plus', 2023, 11, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab A9', 'galaxy-tab-a9', 2023, 12, false, 'google_play'),
  ('samsung', 'tablettes', 'Galaxy Tab A8', 'galaxy-tab-a8', 2022, 13, false, 'google_play'),
  ('samsung', 'montres', 'Galaxy Watch8 Classic', 'galaxy-watch8-classic', 2025, 1, false, 'google_play'),
  ('samsung', 'montres', 'Galaxy Watch8', 'galaxy-watch8', 2025, 2, false, 'google_play'),
  ('samsung', 'montres', 'Galaxy Watch Ultra', 'galaxy-watch-ultra', 2024, 3, false, 'google_play'),
  ('samsung', 'montres', 'Galaxy Watch7', 'galaxy-watch7', 2024, 4, false, 'google_play'),
  ('samsung', 'montres', 'Galaxy Watch FE', 'galaxy-watch-fe', 2024, 5, false, 'google_play'),
  ('samsung', 'montres', 'Galaxy Watch6 Classic', 'galaxy-watch6-classic', 2023, 6, false, 'google_play'),
  ('samsung', 'montres', 'Galaxy Watch6', 'galaxy-watch6', 2023, 7, false, 'google_play'),
  ('samsung', 'montres', 'Galaxy Watch5 Pro', 'galaxy-watch5-pro', 2022, 8, false, 'google_play'),
  ('samsung', 'montres', 'Galaxy Watch5', 'galaxy-watch5', 2022, 9, false, 'google_play'),
  ('xiaomi', 'smartphones', '17 Ultra', '17-ultra', 2026, 1, false, 'google_play'),
  ('xiaomi', 'smartphones', '17 Pro', '17-pro', 2025, 2, false, 'google_play'),
  ('xiaomi', 'smartphones', '17', '17', 2025, 3, false, 'google_play'),
  ('xiaomi', 'smartphones', '15T Pro', '15t-pro', 2025, 4, false, 'google_play'),
  ('xiaomi', 'smartphones', '15T', '15t', 2025, 5, false, 'google_play'),
  ('xiaomi', 'smartphones', '15 Ultra', '15-ultra', 2025, 6, false, 'google_play'),
  ('xiaomi', 'smartphones', '15', '15', 2024, 7, false, 'google_play'),
  ('xiaomi', 'smartphones', '14T Pro', '14t-pro', 2024, 8, false, 'google_play'),
  ('xiaomi', 'smartphones', '14T', '14t', 2024, 9, false, 'google_play'),
  ('xiaomi', 'smartphones', '14 Ultra', '14-ultra', 2024, 10, false, 'google_play'),
  ('xiaomi', 'smartphones', '14', '14', 2023, 11, false, 'google_play'),
  ('xiaomi', 'smartphones', '13T Pro', '13t-pro', 2023, 12, false, 'google_play'),
  ('xiaomi', 'smartphones', '13T', '13t', 2023, 13, false, 'google_play'),
  ('xiaomi', 'smartphones', '13', '13', 2022, 14, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 15 Pro+ 5G', 'redmi-note-15-pro-plus-5g', 2025, 15, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 15 Pro 5G', 'redmi-note-15-pro-5g', 2025, 16, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 15 Pro', 'redmi-note-15-pro', 2025, 17, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 15 5G', 'redmi-note-15-5g', 2025, 18, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 15', 'redmi-note-15', 2025, 19, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 14 Pro+ 5G', 'redmi-note-14-pro-plus-5g', 2024, 20, true, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 14 Pro 5G', 'redmi-note-14-pro-5g', 2024, 21, true, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 14 Pro', 'redmi-note-14-pro', 2024, 22, true, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 14 5G', 'redmi-note-14-5g', 2024, 23, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 14', 'redmi-note-14', 2024, 24, true, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 13 Pro+ 5G', 'redmi-note-13-pro-plus-5g', 2023, 25, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 13 Pro 5G', 'redmi-note-13-pro-5g', 2023, 26, true, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 13 Pro', 'redmi-note-13-pro', 2024, 27, true, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 13 5G', 'redmi-note-13-5g', 2023, 28, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 13', 'redmi-note-13', 2024, 29, true, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 12 Pro 5G', 'redmi-note-12-pro-5g', 2022, 30, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 12 Pro', 'redmi-note-12-pro', 2023, 31, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi Note 12', 'redmi-note-12', 2023, 32, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi 15C', 'redmi-15c', 2025, 33, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi 15', 'redmi-15', 2025, 34, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi 14C', 'redmi-14c', 2024, 35, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi 13C', 'redmi-13c', 2023, 36, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi 13', 'redmi-13', 2024, 37, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi 12', 'redmi-12', 2023, 38, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi A5', 'redmi-a5', 2025, 39, false, 'google_play'),
  ('xiaomi', 'smartphones', 'Redmi A3', 'redmi-a3', 2024, 40, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO F7 Ultra', 'poco-f7-ultra', 2025, 41, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO F7 Pro', 'poco-f7-pro', 2025, 42, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO F7', 'poco-f7', 2025, 43, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO X7 Pro', 'poco-x7-pro', 2025, 44, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO X7', 'poco-x7', 2025, 45, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO F6 Pro', 'poco-f6-pro', 2024, 46, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO F6', 'poco-f6', 2024, 47, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO X6 Pro 5G', 'poco-x6-pro-5g', 2024, 48, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO M6 Pro', 'poco-m6-pro', 2024, 49, false, 'google_play'),
  ('xiaomi', 'smartphones', 'POCO C75', 'poco-c75', 2024, 50, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 11 Pro XL', 'pixel-11-pro-xl', 2026, 1, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 11 Pro', 'pixel-11-pro', 2026, 2, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 11', 'pixel-11', 2026, 3, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 10a', 'pixel-10a', 2026, 4, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 10 Pro Fold', 'pixel-10-pro-fold', 2025, 5, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 10 Pro XL', 'pixel-10-pro-xl', 2025, 6, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 10 Pro', 'pixel-10-pro', 2025, 7, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 10', 'pixel-10', 2025, 8, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 9a', 'pixel-9a', 2025, 9, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 9 Pro Fold', 'pixel-9-pro-fold', 2024, 10, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 9 Pro XL', 'pixel-9-pro-xl', 2024, 11, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 9 Pro', 'pixel-9-pro', 2024, 12, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 9', 'pixel-9', 2024, 13, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 8a', 'pixel-8a', 2024, 14, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 8 Pro', 'pixel-8-pro', 2023, 15, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 8', 'pixel-8', 2023, 16, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 7a', 'pixel-7a', 2023, 17, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 7 Pro', 'pixel-7-pro', 2022, 18, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 7', 'pixel-7', 2022, 19, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 6a', 'pixel-6a', 2022, 20, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 6 Pro', 'pixel-6-pro', 2021, 21, false, 'google_play'),
  ('google', 'smartphones', 'Pixel 6', 'pixel-6', 2021, 22, false, 'google_play'),
  ('huawei', 'smartphones', 'Pura 70 Pro', 'pura-70-pro', 2024, 1, false, 'catalogue'),
  ('huawei', 'smartphones', 'P60 Pro', 'p60-pro', 2023, 2, false, 'catalogue'),
  ('huawei', 'smartphones', 'P50 Pro', 'p50-pro', 2021, 3, false, 'catalogue'),
  ('huawei', 'smartphones', 'Mate 50 Pro', 'mate-50-pro', 2022, 4, false, 'catalogue'),
  ('huawei', 'smartphones', 'Mate 40 Pro', 'mate-40-pro', 2020, 5, false, 'catalogue'),
  ('huawei', 'smartphones', 'nova 12', 'nova-12', 2024, 6, false, 'catalogue'),
  ('huawei', 'smartphones', 'nova 11', 'nova-11', 2023, 7, false, 'catalogue'),
  ('huawei', 'smartphones', 'nova 10', 'nova-10', 2022, 8, false, 'catalogue'),
  ('huawei', 'smartphones', 'nova 9', 'nova-9', 2021, 9, false, 'catalogue'),
  ('huawei', 'smartphones', 'P40 Pro', 'p40-pro', 2020, 10, false, 'catalogue'),
  ('huawei', 'smartphones', 'P40', 'p40', 2020, 11, false, 'catalogue'),
  ('huawei', 'smartphones', 'P40 lite', 'p40-lite', 2020, 12, false, 'catalogue'),
  ('huawei', 'smartphones', 'P30 Pro', 'p30-pro', 2019, 13, false, 'catalogue'),
  ('huawei', 'smartphones', 'P30', 'p30', 2019, 14, false, 'catalogue'),
  ('huawei', 'smartphones', 'P30 lite', 'p30-lite', 2019, 15, false, 'catalogue'),
  ('huawei', 'smartphones', 'Mate 20 Pro', 'mate-20-pro', 2018, 16, false, 'catalogue'),
  ('huawei', 'tablettes', 'MatePad 11.5', 'matepad-11-5', 2023, 1, false, 'catalogue'),
  ('huawei', 'tablettes', 'MatePad Pro 13.2', 'matepad-pro-13-2', 2023, 2, false, 'catalogue'),
  ('honor', 'smartphones', 'Magic7 Pro', 'magic7-pro', 2025, 1, false, 'google_play'),
  ('honor', 'smartphones', '400 Pro', '400-pro', 2025, 2, false, 'google_play'),
  ('honor', 'smartphones', '400', '400', 2025, 3, false, 'google_play'),
  ('honor', 'smartphones', '400 Lite', '400-lite', 2025, 4, false, 'google_play'),
  ('honor', 'smartphones', 'X9c', 'x9c', 2024, 5, false, 'google_play'),
  ('honor', 'smartphones', 'Magic6 Pro', 'magic6-pro', 2024, 6, false, 'google_play'),
  ('honor', 'smartphones', '200 Pro', '200-pro', 2024, 7, false, 'google_play'),
  ('honor', 'smartphones', '200', '200', 2024, 8, false, 'google_play'),
  ('honor', 'smartphones', '200 Lite', '200-lite', 2024, 9, false, 'google_play'),
  ('honor', 'smartphones', 'X9b 5G', 'x9b-5g', 2023, 10, false, 'google_play'),
  ('honor', 'smartphones', 'X8b', 'x8b', 2023, 11, false, 'google_play'),
  ('honor', 'smartphones', 'X7b', 'x7b', 2023, 12, false, 'google_play'),
  ('honor', 'smartphones', 'X6b', 'x6b', 2023, 13, false, 'google_play'),
  ('honor', 'smartphones', 'Magic5 Pro', 'magic5-pro', 2023, 14, false, 'google_play'),
  ('honor', 'smartphones', '90', '90', 2023, 15, false, 'google_play'),
  ('honor', 'smartphones', '90 Lite', '90-lite', 2023, 16, false, 'google_play'),
  ('oppo', 'smartphones', 'Find X9 Pro', 'find-x9-pro', 2025, 1, false, 'google_play'),
  ('oppo', 'smartphones', 'Find X9', 'find-x9', 2025, 2, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno14 Pro 5G', 'reno14-pro-5g', 2025, 3, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno14 5G', 'reno14-5g', 2025, 4, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno14 F 5G', 'reno14-f-5g', 2025, 5, false, 'google_play'),
  ('oppo', 'smartphones', 'Find X8 Pro', 'find-x8-pro', 2024, 6, false, 'google_play'),
  ('oppo', 'smartphones', 'Find X8', 'find-x8', 2024, 7, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno13 Pro 5G', 'reno13-pro-5g', 2024, 8, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno13 5G', 'reno13-5g', 2024, 9, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno13 F', 'reno13-f', 2025, 10, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno12 Pro 5G', 'reno12-pro-5g', 2024, 11, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno12 5G', 'reno12-5g', 2024, 12, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno12 F', 'reno12-f', 2024, 13, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno11 Pro', 'reno11-pro', 2024, 14, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno11', 'reno11', 2024, 15, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno11 F 5G', 'reno11-f-5g', 2024, 16, false, 'google_play'),
  ('oppo', 'smartphones', 'Reno10 5G', 'reno10-5g', 2023, 17, false, 'google_play'),
  ('oppo', 'smartphones', 'A80 5G', 'a80-5g', 2024, 18, false, 'google_play'),
  ('oppo', 'smartphones', 'A60', 'a60', 2024, 19, false, 'google_play'),
  ('oppo', 'smartphones', 'A79 5G', 'a79-5g', 2023, 20, false, 'google_play'),
  ('oppo', 'smartphones', 'A78', 'a78', 2023, 21, false, 'google_play'),
  ('oppo', 'smartphones', 'A58', 'a58', 2023, 22, false, 'google_play'),
  ('oppo', 'smartphones', 'A18', 'a18', 2023, 23, false, 'google_play'),
  ('oneplus', 'smartphones', '15', '15', 2025, 1, false, 'google_play'),
  ('oneplus', 'smartphones', '15R', '15r', 2025, 2, false, 'google_play'),
  ('oneplus', 'smartphones', '13', '13', 2025, 3, false, 'google_play'),
  ('oneplus', 'smartphones', '13R', '13r', 2025, 4, false, 'google_play'),
  ('oneplus', 'smartphones', '13T', '13t', 2025, 5, false, 'google_play'),
  ('oneplus', 'smartphones', '12', '12', 2024, 6, false, 'google_play'),
  ('oneplus', 'smartphones', '12R', '12r', 2024, 7, false, 'google_play'),
  ('oneplus', 'smartphones', '11 5G', '11-5g', 2023, 8, false, 'google_play'),
  ('oneplus', 'smartphones', 'Nord 5', 'nord-5', 2025, 9, false, 'google_play'),
  ('oneplus', 'smartphones', 'Nord 4', 'nord-4', 2024, 10, false, 'google_play'),
  ('oneplus', 'smartphones', 'Nord 3 5G', 'nord-3-5g', 2023, 11, false, 'google_play'),
  ('oneplus', 'smartphones', 'Nord CE5', 'nord-ce5', 2025, 12, false, 'google_play'),
  ('oneplus', 'smartphones', 'Nord CE4', 'nord-ce4', 2024, 13, false, 'google_play'),
  ('oneplus', 'smartphones', 'Nord CE4 Lite 5G', 'nord-ce4-lite-5g', 2024, 14, false, 'google_play'),
  ('oneplus', 'smartphones', 'Nord CE 3 Lite 5G', 'nord-ce-3-lite-5g', 2023, 15, false, 'google_play'),
  ('motorola', 'smartphones', 'moto g86 5G', 'moto-g86-5g', 2025, 1, false, 'google_play'),
  ('motorola', 'smartphones', 'moto g85 5G', 'moto-g85-5g', 2024, 2, false, 'google_play'),
  ('motorola', 'smartphones', 'moto g84 5G', 'moto-g84-5g', 2023, 3, false, 'google_play'),
  ('motorola', 'smartphones', 'moto g75 5G', 'moto-g75-5g', 2024, 4, false, 'google_play'),
  ('motorola', 'smartphones', 'moto g64 5G', 'moto-g64-5g', 2024, 5, false, 'google_play'),
  ('motorola', 'smartphones', 'moto g56 5G', 'moto-g56-5g', 2025, 6, false, 'google_play'),
  ('motorola', 'smartphones', 'moto g55 5G', 'moto-g55-5g', 2024, 7, false, 'google_play'),
  ('motorola', 'smartphones', 'moto g54 5G', 'moto-g54-5g', 2023, 8, false, 'google_play'),
  ('realme', 'smartphones', '14 Pro+ 5G', '14-pro-plus-5g', 2025, 1, false, 'google_play'),
  ('realme', 'smartphones', '14 Pro 5G', '14-pro-5g', 2025, 2, false, 'google_play'),
  ('realme', 'smartphones', '13 Pro+ 5G', '13-pro-plus-5g', 2024, 3, false, 'google_play'),
  ('realme', 'smartphones', '13 Pro 5G', '13-pro-5g', 2024, 4, false, 'google_play'),
  ('realme', 'smartphones', '12 Pro+ 5G', '12-pro-plus-5g', 2024, 5, false, 'google_play'),
  ('realme', 'smartphones', '12 Pro 5G', '12-pro-5g', 2024, 6, false, 'google_play'),
  ('realme', 'smartphones', 'C75', 'c75', 2024, 7, false, 'google_play'),
  ('realme', 'smartphones', 'C67', 'c67', 2023, 8, false, 'google_play'),
  ('realme', 'smartphones', 'C63', 'c63', 2024, 9, false, 'google_play'),
  ('realme', 'smartphones', 'C55', 'c55', 2023, 10, false, 'google_play'),
  ('vivo', 'smartphones', 'V50', 'v50', 2025, 1, false, 'google_play'),
  ('vivo', 'smartphones', 'V40', 'v40', 2024, 2, false, 'google_play'),
  ('vivo', 'smartphones', 'V30', 'v30', 2024, 3, false, 'google_play'),
  ('vivo', 'smartphones', 'Y28', 'y28', 2024, 4, false, 'google_play'),
  ('vivo', 'smartphones', 'Y17', 'y17', 2019, 5, false, 'google_play'),
  ('vivo', 'smartphones', 'Y03', 'y03', 2024, 6, false, 'google_play'),
  ('tecno', 'smartphones', 'CAMON 40 Pro', 'camon-40-pro', 2025, 1, false, 'google_play'),
  ('tecno', 'smartphones', 'CAMON 40', 'camon-40', 2025, 2, false, 'google_play'),
  ('tecno', 'smartphones', 'CAMON 30', 'camon-30', 2024, 3, false, 'google_play'),
  ('tecno', 'smartphones', 'CAMON 20', 'camon-20', 2023, 4, false, 'google_play'),
  ('tecno', 'smartphones', 'SPARK 40 Pro', 'spark-40-pro', 2025, 5, false, 'google_play'),
  ('tecno', 'smartphones', 'SPARK 40', 'spark-40', 2025, 6, false, 'google_play'),
  ('tecno', 'smartphones', 'SPARK 30 Pro', 'spark-30-pro', 2024, 7, false, 'google_play'),
  ('tecno', 'smartphones', 'SPARK 30', 'spark-30', 2024, 8, false, 'google_play'),
  ('tecno', 'smartphones', 'SPARK 20 Pro', 'spark-20-pro', 2023, 9, false, 'google_play'),
  ('tecno', 'smartphones', 'SPARK 20', 'spark-20', 2023, 10, false, 'google_play'),
  ('infinix', 'smartphones', 'NOTE 50', 'note-50', 2025, 1, false, 'google_play'),
  ('infinix', 'smartphones', 'NOTE 40 Pro', 'note-40-pro', 2024, 2, false, 'google_play'),
  ('infinix', 'smartphones', 'NOTE 40', 'note-40', 2024, 3, false, 'google_play'),
  ('infinix', 'smartphones', 'NOTE 30', 'note-30', 2023, 4, false, 'google_play'),
  ('infinix', 'smartphones', 'HOT 50', 'hot-50', 2024, 5, false, 'google_play'),
  ('infinix', 'smartphones', 'HOT 40', 'hot-40', 2023, 6, false, 'google_play'),
  ('infinix', 'smartphones', 'HOT 40i', 'hot-40i', 2023, 7, false, 'google_play'),
  ('sony', 'consoles', 'PlayStation 5 Pro', 'playstation-5-pro', 2024, 1, true, 'catalogue'),
  ('sony', 'consoles', 'PlayStation 5 Slim', 'playstation-5-slim', 2023, 2, true, 'catalogue'),
  ('sony', 'consoles', 'PlayStation 5', 'playstation-5', 2020, 3, true, 'catalogue'),
  ('sony', 'consoles', 'PlayStation 5 Digital Edition', 'playstation-5-digital-edition', 2020, 4, false, 'catalogue'),
  ('sony', 'consoles', 'PlayStation 4 Pro', 'playstation-4-pro', 2016, 5, false, 'catalogue'),
  ('sony', 'consoles', 'PlayStation 4 Slim', 'playstation-4-slim', 2016, 6, false, 'catalogue'),
  ('sony', 'consoles', 'PlayStation 4', 'playstation-4', 2013, 7, false, 'catalogue'),
  ('sony', 'consoles', 'PlayStation Portal', 'playstation-portal', 2023, 8, false, 'catalogue'),
  ('sony', 'consoles', 'Manette DualSense Edge', 'manette-dualsense-edge', 2023, 9, false, 'catalogue'),
  ('sony', 'consoles', 'Manette DualSense', 'manette-dualsense', 2020, 10, true, 'catalogue'),
  ('sony', 'consoles', 'Manette DualShock 4', 'manette-dualshock-4', 2013, 11, false, 'catalogue'),
  ('nintendo', 'consoles', 'Switch 2', 'switch-2', 2025, 1, true, 'catalogue'),
  ('nintendo', 'consoles', 'Switch OLED', 'switch-oled', 2021, 2, true, 'catalogue'),
  ('nintendo', 'consoles', 'Switch', 'switch', 2017, 3, true, 'catalogue'),
  ('nintendo', 'consoles', 'Switch Lite', 'switch-lite', 2019, 4, false, 'catalogue'),
  ('nintendo', 'consoles', 'Joy-Con', 'joy-con', 2017, 5, false, 'catalogue'),
  ('nintendo', 'consoles', 'Manette Switch Pro', 'manette-switch-pro', 2017, 6, false, 'catalogue'),
  ('microsoft', 'consoles', 'Xbox Series X', 'xbox-series-x', 2020, 1, false, 'catalogue'),
  ('microsoft', 'consoles', 'Xbox Series S', 'xbox-series-s', 2020, 2, false, 'catalogue'),
  ('microsoft', 'consoles', 'Xbox One X', 'xbox-one-x', 2017, 3, false, 'catalogue'),
  ('microsoft', 'consoles', 'Xbox One S', 'xbox-one-s', 2016, 4, false, 'catalogue'),
  ('microsoft', 'consoles', 'Xbox One', 'xbox-one', 2013, 5, false, 'catalogue'),
  ('microsoft', 'consoles', 'Manette Xbox', 'manette-xbox', 2020, 6, false, 'catalogue'),
  ('valve', 'consoles', 'Steam Deck OLED', 'steam-deck-oled', 2023, 1, false, 'catalogue'),
  ('valve', 'consoles', 'Steam Deck', 'steam-deck', 2022, 2, false, 'catalogue')
) as v(brand_slug, category_slug, name, slug, release_year, sort_order, is_popular, source)
join public.brands b on b.slug = v.brand_slug
join public.device_categories c on c.slug = v.category_slug
on conflict (brand_id, slug) do nothing;
